[project]
name = "ai_seo_forecasting"
version = "0.1.0"
description = "ai-seo-forecasting using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.201.1,<1.0.0"
]

[project.scripts]
ai_seo_forecasting = "ai_seo_forecasting.main:run"
run_crew = "ai_seo_forecasting.main:run"
train = "ai_seo_forecasting.main:train"
replay = "ai_seo_forecasting.main:replay"
test = "ai_seo_forecasting.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
