[global]
index-url=https://bsstfs.pkgs.visualstudio.com/DealFlow/_packaging/dealflow/pypi/simple/
trusted-host=bsstfs.pkgs.visualstudio.com
always-trusted=true

[dev]
extra-index-url=https://pypi.org/simple